# Week01b - Example

### Example01 - 텐서플로우의 변수 텐서 생성 코드

In [1]:
import tensorflow as tf
# 2차원 텐서 생성 예제
x = tf.constant([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
print(x, end="\n\n")
# 상수 텐서 생성 연산 예제
constant_a = tf.constant(2)
constant_b = tf.constant(3)
c = constant_a + constant_b
print(c, end="\n\n")

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)

tf.Tensor(5, shape=(), dtype=int32)



### Example02 - 텐서플로우의 변수 텐서 생성 코드

In [2]:
import tensorflow as tf
# 2차원 텐서 생성 예제
x = tf.Variable(initial_value=[[1,2,3,4],
                               [5,6,7,8],
                               [9,10,11,12]], name="x")
print(x, end="\n\n")
# 변수 텐서 생성 연산 예제
variable_a = tf.Variable(initial_value=2)
variable_b = tf.Variable(initial_value=3)
c = variable_a + variable_b
print(c, end="\n\n")

<tf.Variable 'x:0' shape=(3, 4) dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])>

tf.Tensor(5, shape=(), dtype=int32)



### Example03 - 텐서 연산자 생성 코드

In [3]:
import tensorflow as tf

x = tf.constant([[1, 2]])
y = tf.constant([[1, 2]])

negMatrix = tf.negative(x)
print(negMatrix, end="\n\n")

negMatrix.numpy()
z=tf.add(x, y)
tf.subtract(x, y)
tf.multiply(x, y)
tf.pow(x, y)
tf.exp(1.1) #float지정
tf.sqrt(0.3) #float지정
tf.divide(x, y)
tf.truediv(x, y)
tf.math.floordiv(x, y)
tf.math.mod(x, y)
print(z.numpy(), end="\n\n")

tensor1 = tf.constant([1, 2, 3],dtype=tf.int32) 
tensor2 = tf.ones([3],dtype=tf.int32)

result = tensor1 + tensor2
print(result, end="\n\n")

tf.Tensor([[-1 -2]], shape=(1, 2), dtype=int32)

[[2 4]]

tf.Tensor([2 3 4], shape=(3,), dtype=int32)



### Example04 - 텐서 변환

In [4]:
import tensorflow as tf
import numpy as np

# Use | tf.convert_to_tensor()
m1=[[1.0, 2.0], [3.0, 4.0]]
m2=np.array([[1.0, 2.0],
             [3.0, 4.0]], dtype=np.float32)
t1=tf.convert_to_tensor(m1, dtype=tf.float32)
t2=tf.convert_to_tensor(m2, dtype=tf.float32)
print(t1)
print(t2)
# 불타입 텐서 생성
bool_tensor = tf.constant([True,False,True], dtype=tf.bool)
# 불형 텐서를 정수형으로 변환(T -> 1, F -> 0)
int_tensor = tf.cast(bool_tensor, dtype=tf.int32)
print(int_tensor)

# 정수형 텐서 생성
x = tf.constant([1,2,3,4], dtype=tf.int32)
# 정수형 텐서를 실수형으로 변환
x_float = tf.cast(x, dtype=tf.float32)
print(x_float)

# 1차원 텐서 생성
tensor_1d = tf.constant([1, 2, 3, 4, 5, 6], dtype=tf.int32)
# 1차원 텐서를 2x3의 2차원 텐서로 변환
tensor_2d = tf.reshape(tensor_1d, shape=(2, 3))
print("[ tensor_2d ]", end="\n")
print(tensor_2d, end="\n\n\n")
# 2차원 텐서 생성
tensor_2d = tf.constant([[1, 2, 3],
                         [4, 5, 6]], dtype=tf.int32)
# 2차원 텐서를 3차원 텐서로 변환
tensor_3d = tf.reshape(tensor_2d, shape=(2, 1, 3))#((3, 1, 3) >> 1행 3열이 2개)
print("[ tensor_3d ]", end="\n")
print(tensor_3d, end="\n\n\n")
# 예시로, 8개의 샘플이 있고 각 샘플은 3개의 피처를 가짐
tensor_batch = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], 
                            [13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]], dtype=tf.int32)
# 배치 크기를 4로 변경 (2x4 배치로 변환)
reshaped_batch = tf.reshape(tensor_batch, shape=(4, 2, 3))
print("[ reshaped_batch ]", end="\n")
print(reshaped_batch, end="\n\n\n")

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor([1 0 1], shape=(3,), dtype=int32)
tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)
[ tensor_2d ]
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


[ tensor_3d ]
tf.Tensor(
[[[1 2 3]]

 [[4 5 6]]], shape=(2, 1, 3), dtype=int32)


[ reshaped_batch ]
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]], shape=(4, 2, 3), dtype=int32)


